repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c '.venv/bin/pytest -v -x -s --cov=app -vv --cov-report=term-missing'
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit]
